### ISSUE TITLE
폰트 적용 관련 이슈

### ISSUE THREAD

**Issue by jiho3894** [sparta-team6/CO-UP-TEAM-FE#23]
현재 이슈
 - tailwind를 사용할때 제공하는 기본 폰트를 제외한 다른 외부 폰트가 필요했던 상태였지만 tailwind 역시 정확하게 동작하지않는 이슈가 있었음

방법
1. css에 모듈을 새로 만듦
```css
@font-face {
  font-family: "AppleSDGothicNeo";
  font-weight: 700;
  src: url("../assets/fonts/AppleSDGothicNeoB.woff") format("woff");
}
```
